package Windows;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import Flappy.GameFlappy;
import Flappy.RenderAndKey;
import settingsClass.MyBoolean;
import settingsClass.SnakeSettingsSaveClass;

import java.applet.Applet;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author user
 */
public class MenuWindow extends javax.swing.JFrame {

    SnakeSettingsSaveClass snakeSettingsSaveClass;


    /**
     * Creates new form MenuWindow
     */
    public MenuWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">

            MyBoolean showPatch=new MyBoolean(false);




    ActionListener actionListener = new ActionListener() {


        @Override
        public void actionPerformed(ActionEvent e) {
            buttonWasPressed(e);
        }
    };



    public void buttonWasPressed(ActionEvent e){

        GameFlappy gameFlappy;


        if(e.getSource()==playFlappyButton){
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new FlappyGameWindow(1).setVisible(true);
                }
            });
        }

        if(e.getSource()==flappyAiButton){
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new FlappyGameWindow(2).setVisible(true);
                }
            });
        }

        if(e.getSource()== playSnakeButton){
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    snakeSettingsSaveClass.setAi(false);
                    new SnakeGameWindow(1,snakeSettingsSaveClass).setVisible(true);
                }
            });
        }

        if(e.getSource()== SnakeAiButton){
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    System.out.println("wywołałem z "+showPatch);
                    snakeSettingsSaveClass.setAi(true);
                    new SnakeGameWindow(2,snakeSettingsSaveClass).setVisible(true);

                }
            });
        }

        if(e.getSource()== SnakeSettingsButton){
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new SnakeSettingsWindow(snakeSettingsSaveClass).setVisible(true);
                }
            });
        }




    }

    private void initComponents() {
        snakeSettingsSaveClass=new SnakeSettingsSaveClass();

        applet=new RenderAndKey(1);

        jPanel1 = new javax.swing.JPanel();
        playFlappyButton = new javax.swing.JButton();
        playSnakeButton = new javax.swing.JButton();
        flappyAiButton = new javax.swing.JButton();
        SnakeAiButton = new javax.swing.JButton();
        flappySettingButton = new javax.swing.JButton();
        SnakeSettingsButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        playFlappyButton.setText("Play Flappy");
        playFlappyButton.addActionListener(actionListener);
        flappyAiButton.addActionListener(actionListener);

        playSnakeButton.addActionListener(actionListener);
        SnakeAiButton.addActionListener(actionListener);

        SnakeSettingsButton.addActionListener(actionListener);

        playSnakeButton.setText("Play Snake");

        flappyAiButton.setText("Flappy Ai");

        SnakeAiButton.setText("Snake AI");

        flappySettingButton.setText("Flappy Settings");

        SnakeSettingsButton.setText("Snake Settings");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(playSnakeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(playFlappyButton, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))
                                .addGap(99, 99, 99)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(flappyAiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(SnakeAiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(72, 72, 72)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(SnakeSettingsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(flappySettingButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(playFlappyButton, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                                        .addComponent(flappyAiButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(flappySettingButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(playSnakeButton, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                                        .addComponent(SnakeAiButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(SnakeSettingsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(329, 329, 329))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton flappyAiButton;
    private javax.swing.JButton flappySettingButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton playFlappyButton;
    private javax.swing.JButton playSnakeButton;
    private javax.swing.JButton SnakeAiButton;
    private javax.swing.JButton SnakeSettingsButton;
    private Applet applet;
    // End of variables declaration
}
