package Windows;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import settingsClass.SnakeSettingsSaveClass;

import javax.swing.*;

/**
 *
 * @author user
 */
public class SnakeSettingsWindow extends javax.swing.JFrame {


    SnakeSettingsSaveClass snakeSettingsSaveClass;

    /**
     * Creates new form SnakeSettingsWindow
     */
    public SnakeSettingsWindow(SnakeSettingsSaveClass snakeSettingsSaveClass) {
        this.snakeSettingsSaveClass=snakeSettingsSaveClass;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    public void actionListenerRadioButton(java.awt.event.ActionEvent evt) {
        RadioButton1ActionPerformed(evt);
    }
    public void actionListenerButton(java.awt.event.ActionEvent evt) {
        ButtonActionPerformed(evt);
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        textXSize = new javax.swing.JTextField();
        textYSize = new javax.swing.JTextField();
        setYSize = new javax.swing.JButton();
        showPathButton = new javax.swing.JRadioButton();
        lableSizeX = new javax.swing.JLabel();
        lableSizeY = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        setXSize = new javax.swing.JButton();
        setDefButton = new javax.swing.JButton();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
                jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
                jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 204));

        setYSize.setText("Set");
        setYSize.addActionListener(this::actionListenerButton);

        showPathButton.setText("AI show path");
        showPathButton.addActionListener(this::actionListenerRadioButton);

        lableSizeX.setText("Set size X 10-50");

        lableSizeY.setText("Set size Y 10-50");

        jLabel3.setText("MAP SIZE ");

        setXSize.setText("Set");
        setXSize.addActionListener(this::actionListenerButton);

        setDefButton.setText("set defaults");
        setDefButton.addActionListener(this::actionListenerButton);

        textXSize.setText(String.valueOf(snakeSettingsSaveClass.getMapSizeX()));
        textYSize.setText(String.valueOf(snakeSettingsSaveClass.getMapSizeY()));
        showPathButton.setSelected(snakeSettingsSaveClass.isShowPatch());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(34, 34, 34)
                                                .addComponent(showPathButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(lableSizeY, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(lableSizeX, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(23, 23, 23)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(textXSize)
                                                        .addComponent(textYSize, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(8, 8, 8)
                                                                .addComponent(setYSize))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(setXSize))))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(setDefButton)))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(showPathButton)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(textXSize, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lableSizeX, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(setXSize))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(textYSize, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(setYSize)
                                        .addComponent(lableSizeY, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(setDefButton)
                                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void RadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        snakeSettingsSaveClass.setShowPatch(showPathButton.isSelected());
    }

    private void ButtonActionPerformed(java.awt.event.ActionEvent evt) {
        if(evt.getSource()==setXSize){
            if(Integer.valueOf(textXSize.getText())>=10&&Integer.valueOf(textXSize.getText())<=50){
                snakeSettingsSaveClass.setMapSizeX(Integer.valueOf(textXSize.getText()));
            }
        }else if(evt.getSource()==setYSize){
            if(Integer.valueOf(textYSize.getText())>=10&&Integer.valueOf(textYSize.getText())<=50){
                snakeSettingsSaveClass.setMapSizeY(Integer.valueOf(textYSize.getText()));
            }
        }else if(evt.getSource()==setDefButton) {
            snakeSettingsSaveClass.SetDefaults();
            textXSize.setText(String.valueOf(snakeSettingsSaveClass.getMapSizeX()));
            textYSize.setText(String.valueOf(snakeSettingsSaveClass.getMapSizeY()));
        }
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify
    private javax.swing.JButton setDefButton;
    private javax.swing.JLabel lableSizeX;
    private javax.swing.JLabel lableSizeY;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JRadioButton showPathButton;
    private javax.swing.JButton setXSize;
    private javax.swing.JButton setYSize;
    private javax.swing.JTextField textXSize;
    private javax.swing.JTextField textYSize;
    // End of variables declaration
}

